# hBoss 0.1-alpha-1 by Benjozork

delay: 20

messages:
    ## Help messages
    help_header: ' &7&m+----------&r &6Boss &7&m----------+'
    help_spawn: ' &6/hboss spawn <name> <type> <health multiplier>'
    help_spawn_desc: '&7   - &8Creates a new spawn.'
    help_set: ' &6/hboss set <spawn> name/type/health multiplier/delay/loc <value>'
    help_set_desc: '&7   - &8Sets a spawn parameter.'
    help_list: '  &6/hboss list'
    help_list_desc: '&7   - &8Lists all spawns'
    help_types: ' &6/hboss types'
    help_types_desc: '&7   - &8Lists all mob types with configurations.'
    help_footer: '&8Pages: &6%pages% &7&m'
    # Help page 2
    help_delete: ' &6/hboss delete [spawn]'
    help_delete_desc: '&7   - &8Delete a spawn.'
    help_effect_list: ' &6/hboss effect list [spawn]'
    help_effect_list_desc: '&7   - &8List all effects on spawn, or available.'
    help_effect_add: '  &6/hboss effect add <spawn> <effect>'
    help_effect_add_desc: '&7   - &8Add an effect to a spawn.'
    help_effect_remove: ' &6/hboss effect remove <spawn> <effect>'
    help_effect_remove_desc: '&7   - &8Remove an effect of a spawn.'
    ## Error messages
    not_enough_args: '&cNot enough arguments (%curr%/%req%) for command: /hboss %command%.'
    not_a_number: '&cError on input "%string%" for argument "%arg%": Number expected.'
    invalid_mob_type: '&cInavlid mob type "%string%".'
    invalid_spawn_name: '&cInvalid spawn name "%string%".'
    invalid_paramter: '&cInvalid parameter "%string%".'
    ## Info messages
    spawn_created: '&aBoss spawn "%name%" created at your location.'
    spawn_list_header: '&7Boss spawns (%count%):'
    spawn_list_name: '&8 - &a%name%:'
    spawn_list_info: '&7    Type: &a%type% &7Health multiplier: &a%healthMultiplier%'
    spawn_list_attributes: '&7    Attributes: &a%attributes%'
    spawn_list_none: '&cNo spawns registered.'
    spawn_no_attributes: '&anone.'
    spawn_delete_deleted: '&aSpawn "%name%" deleted.'
    spawn_set_value_set: '&aValue "%param%" set to "%value%" for spawn "%name%".'
