# hBoss 0.1-alpha-1 by Benjozork

messages:
    ## Help messages
    help_header: ' &7&m+----------&r &6Boss &7&m----------+'
    help_spawn: ' &6/hboss spawn <name> <type> <health multiplier>'
    help_spawn_desc: '&7   - &8Creates a new spawn.'
    help_set: ' &6/hboss set <spawn> name/type/health multiplier/delay <value>'
    help_set_desc: '&7   - &8Sets a spawn parameter.'
    help_list: '  &6/hboss list'
    help_list_desc: '&7   - &8Lists all spawns'
    help_types: ' &6/hboss types'
    help_types_desc: '&7   - &8Lists all mob types with configurations.'
    help_footer: '&8Pages: &6%pages% &7&m'
    # Page 2
    help_info: ' &6/hboss info [spawn]'
    help_info_desc: '&7   - &8Give info on a spawn.'
    help_effect_list: ' &6/hboss effect list [spawn]'
    help_effect_list_desc: '&7   - &8List all effects on spawn, or available.'
    help_effect_add: '  &6/hboss effect add <spawn> <effect>'
    help_effect_add_desc: '&7   - &8Add an effect to a spawn.'
    help_effect_remove: ' &6/hboss effect remove <spawn> <effect>'
    help_effect_remove_desc: '&7   - &8Remove an effect of a spawn.'
    ## Error messages
    not_enough_args: '&CNot enough arguments (%curr%/%req%) for command: /boss %command%'
    invalid_mob_type: '&cInavlid mob type "%type%.;'
